### ISSUE TITLE
Failed to change lights

### ISSUE THREAD

**Issue by paradox-sp** [muckelba/dynamic-lights-homeassistant#2]
I have followed every step but still get failed to change lights. also check home assistant logs and their is no web hook request

**Comment by muckelba** [comment]
Sounds like the issue is on the spicetify side. Have you checked the console logs (`spicetify enable-devtools`, right click anywhere in spotify and select `Show DevTools`)?

**Comment by paradox-sp** [comment]
here is the problem --->
dynamic-lights-homeassistant.js?time=1730058845589:1 
Mixed Content: The page at 'https://xpui.app.spotify.com/index.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://192.168.1.2:8563/api/webhook/-tSqwsdawdcasdwervasjhq4Oz'. This request has been blocked; the content must be served over HTTPS.

**Comment by muckelba** [comment]
You need to have a valid SSL certificate for your homeassistant installation unfortunately. That's a security feature of Chrome. I guess i'll add an error when trying to setup the URL with plain HTTP.
