### ISSUE TITLE
Pretty please a little guide on how to make a https home assistant instance 

### ISSUE THREAD

**Issue by HannistHK** [muckelba/dynamic-lights-homeassistant#3]
Hey I can't seem to do it after trying for days.... Can you maybe type out a small guide for beginners like me? Thanks a lot 🙏

**Comment by muckelba** [comment]
Hey, setting up SSL for your homeassistant installation varies heavily on how you are running homeassistant and your type of internet connection.
But I think this video is a good guide using a Cloudflare Tunnel: https://www.youtube.com/watch?v=xXAwT9N-7Hw

**Comment by HannistHK** [comment]
Hey thanks a lot, I didn't knew tunnels could work. Also big thanks for your contribution towards this project. Not all heros wear capes!
