### ISSUE TITLE
colors not changing 

### ISSUE THREAD

**Issue by HannistHK** [muckelba/dynamic-lights-homeassistant#4]
So i managed to make a SSL instance through Nabu Casa and it goes something like "https://ui.nabu.casa". i verified its ssl status and entered the correct webhook in its place but still no trigger.  Heres my YAML code too.
![image](https://github.com/user-attachments/assets/b94c8b3c-3a99-4afe-b504-d3309bc178ea)

**Comment by muckelba** [comment]
1. Do you see traces in the past? (Click on the top right "Traces" button when editing the automation)
2. Do you see any errors in spotify when changing the title?
3. Do you see any errors in the spicetify console when changing the title? (`spicetify enable-devtools`, right click anywhere in spotify and select Show DevTools)

**Comment by HannistHK** [comment]
> 1. Do you see traces in the past? (Click on the top right "Traces" button when editing the automation)
> 2. Do you see any errors in spotify when changing the title?
> 3. Do you see any errors in the spicetify console when changing the title? (`spicetify enable-devtools`, right click anywhere in spotify and select Show DevTools)
> 



1. These are the traces i see ![Screenshot_20241104-233156.png](https://github.com/user-attachments/assets/37ffd3e5-3cb2-4bad-8dc7-f39905d08d05)


As for 2. And 3. I'll send in a bit

**Comment by HannistHK** [comment]
Heres the follow up:

2. No error when changing titles 
3. heres the devlog console 
![image](https://github.com/user-attachments/assets/4aa305f0-edca-45e3-8152-e4e5aa94549d)

**Comment by HannistHK** [comment]
Still waiting....

**Comment by muckelba** [comment]
Go to the dev console again, change to the `Network` tab, click on the grey circle 🚫 right next to the red icon. Skip to the next song. Do you see any request that is caused by `dynamic-lights-homeassistant.js` in the `Initiator` column? If yes, the extension is probably fine and something is not working on the homeassistant side.

**Comment by HannistHK** [comment]
Hey! It turns out indeed its the dynamic lights request thats failing. have a look. 
![image](https://github.com/user-attachments/assets/bb523d4c-18e8-492c-987a-ae0bb2158b97)

im a bit lost tho, ive verified my nabu casa instance is working with a valid ssl but still this...

**Comment by HannistHK** [comment]
Also im getting these errors too:


dynamic-lights-homeassistant.js?time=1730977232058:1 Error turning on light: v {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}code: "ERR_NETWORK"config: {transitional: {…}, adapter: Array(3), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}message: "Network Error"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}stack: "AxiosError: Network Error\n    at f.onerror (https://cdn.jsdelivr.net/gh/muckelba/dynamic-lights-homeassistant@main/dist/dynamic-lights-homeassistant.js?time=1730977232058:1:22563)\n    at k.request (https://cdn.jsdelivr.net/gh/muckelba/dynamic-lights-homeassistant@main/dist/dynamic-lights-homeassistant.js?time=1730977232058:1:29675)\n    at async Tt (https://cdn.jsdelivr.net/gh/muckelba/dynamic-lights-homeassistant@main/dist/dynamic-lights-homeassistant.js?time=1730977232058:1:38022)"[[Prototype]]: Error
Tt @ dynamic-lights-homeassistant.js?time=1730977232058:1



and 



  POST https://<my nabu casa instance>:.ui.nabu.casa/api/webhook<>my webhook:
net::ERR_CONNECTION_CLOSED
(anonymous) @ dynamic-lights-homeassistant.js?time=1730977232058:1
xhr @ dynamic-lights-homeassistant.js?time=1730977232058:1
ft @ dynamic-lights-homeassistant.js?time=1730977232058:1
_request @ dynamic-lights-homeassistant.js?time=1730977232058:1
request @ dynamic-lights-homeassistant.js?time=1730977232058:1
(anonymous) @ dynamic-lights-homeassistant.js?time=1730977232058:1
(anonymous) @ dynamic-lights-homeassistant.js?time=1730977232058:1
Tt @ dynamic-lights-homeassistant.js?time=1730977232058:1
await in Tt (async)
(anonymous) @ dynamic-lights-homeassistant.js?time=1730977232058:1
dispatchEvent @ spicetifyWrapper.js:16
(anonymous) @ spicetifyWrapper.js:979
_dispatchFromStore @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
a @ vendor~xpui.js:1
t @ vendor~xpui.js:1
postMessage (async)
c @ vendor~xpui.js:1
emit @ vendor~xpui.js:1
emit @ xpui.js:1
(anonymous) @ xpui.js:1
(anonymous) @ vendor~xpui.js:1
onSuccess @ xpui.js:1

**Comment by HannistHK** [comment]
im getting these errors in console: 
![image](https://github.com/user-attachments/assets/7d4c03e5-ef14-4c72-b6b1-8e558eabba0e)

**Comment by HannistHK** [comment]
Getting these errors ![1730983764307.jpg](https://github.com/user-attachments/assets/982d9675-3bba-4be9-9564-169e5026980b)

**Comment by KinteLiX** [comment]
Edit the webhook trigger as YAML and make sure local_only is false.
![Screenshot_20241109_132039](https://github.com/user-attachments/assets/a6d937eb-92e0-47d3-995e-b2a75b222d16)

**Comment by muckelba** [comment]
Yea, i guess you need to set `local_only` when using nabu casas solution. Please try that @HannistHK 

@KinteLiX interesting, i'll add it to the README, ty

**Comment by KinteLiX** [comment]
> Yea, i guess you need to set `local_only` when using nabu casas solution. Please try that @HannistHK
> 
> @KinteLiX interesting, i'll add it to the README, ty

I'm using cloudflared and had to do this as well. You're welcome!

**Comment by HannistHK** [comment]
Hey it works now!!! 

Thanks @muckelba and @KinteLiX for helping me out, means a lot!

**Comment by HannistHK** [comment]
Sorry for repeatedly making new comments but there should be a way to saturate the colors a bit mine look a bit bland because of each led not being individually addressable.
